image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'curl https://sh.rustup.rs -sSf | sh && 1 && source /workspace/.cargo/env && rustup install nightly && rustup install stable && rustup target add wasm32-unknown-unknown --toolchain nightly' # runs during prebuild
  - command: echo 'make init && make build'